### ISSUE TITLE
Refactoring checklist

### ISSUE THREAD

**Issue by prihoda** [the-bots/botshot#13]
- [x] Make private methods private
- [x] Python 3.5 incompatibility bug
- [x] Do not import classes in settings file, use strings and importlib

**Comment by mzilinec** [comment]
(1) done

**Comment by mzilinec** [comment]
Python 3.4: Definitely incompatible - doesn't support typing hints

**Comment by mzilinec** [comment]
Python 3.5: Already compatible, so it seems.

**Comment by mzilinec** [comment]
**Python 3.7: Not compatible - waiting for Celery 4.3.**
